package vn.nitrogen.administration.dto;

public enum SecurityEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    UNAUTHORIZED_ACCESS,
    RATE_LIMITED,
    REGISTRATION_SUCCESS,
    REGISTRATION_DUPLICATE_EMAIL,
    EMAIL_VERIFICATION_SUCCESS,
    EMAIL_VERIFICATION_FAILURE
}
